### ISSUE TITLE
install process

### ISSUE THREAD

**Issue by SakuraCart** [eekwong/express-osc#1]
Hi!

I'm new to node.js and thought that this would be a great app to start with!

How do you install this?
Also, have you updated this recently?

**Comment by eekwong** [comment]
How do you install this?

Since you are new to node.js, you have to make sure your node.js installation is working.
node -e "console.log('abc');"
should return abc in your console.

Then you have to install mongodb.

At last, download my code in zip, and unzip somewhere, and launch the application by typing
node app.js

What's your Operating System?

have you updated this recently?

No, but I believe a chat feature like the one in facebook is really cool, and it's not that hard to implement either.

**Comment by SakuraCart** [comment]
Thanks for your help!

mongodb and node are working.

I'm on osx 10.8.1 and installed the latest versions of express, node and mongo

I asked if you have updated also because maybe my versions of express and node might be too new ...

the errors that I'm getting are:

500 TypeError: Invalid select() argument. Must be a string or object.
at Query.select (/Users/L/Sites/eekwong/node_modules/mongoose/lib/query.js:1062:11)
at Function.find (/Users/L/Sites/eekwong/node_modules/mongoose/lib/model.js:874:9)
at Object.exports.getPlans (/Users/L/Sites/eekwong/models.js:89:8)
at /Users/L/Sites/eekwong/app.js:78:10
at callbacks (/Users/L/Sites/eekwong/node_modules/express/lib/router/index.js:165:11)
at param (/Users/L/Sites/eekwong/node_modules/express/lib/router/index.js:139:11)
at pass (/Users/L/Sites/eekwong/node_modules/express/lib/router/index.js:146:5)
at Router._dispatch (/Users/L/Sites/eekwong/node_modules/express/lib/router/index.js:173:5)
at Object.router (/Users/L/Sites/eekwong/node_modules/express/lib/router/index.js:33:10)
at next (/Users/L/Sites/eekwong/node_modules/express/node_modules/connect/lib/proto.js:190:15)

I'm still new to node so I may have missed something.

Any help would be appreciated!

Also, I do like your idea!

**Comment by eekwong** [comment]
I'll try the latest stack tomorrow or so, and let you know.

**Comment by eekwong** [comment]
Well, there have been a lot of api changes in express and mongoose. I don't have the time right now, so I just tried the most recent working version of the libs:

Verified the nodejs and mongodb is working...

```
root@Config61288VM0:~/express-osc# pwd
/root/express-osc
root@Config61288VM0:~/express-osc# mongo
MongoDB shell version: 2.2.0
connecting to: test
> exit
bye
root@Config61288VM0:~/express-osc# node --version
v0.8.9
root@Config61288VM0:~/express-osc# ls -l
total 24
-rw-r--r-- 1 root root 5659 Sep 21 16:05 app.js
-rw-r--r-- 1 root root 2890 Sep 21 16:05 models.js
-rw-r--r-- 1 root root  219 Sep 21 16:05 package.json
drwxrwxr-x 5 root root 4096 Sep 21 16:05 public
-rw-r--r-- 1 root root    0 Sep 21 16:05 README
drwxrwxr-x 4 root root 4096 Sep 21 16:05 views
```

Install 4 libraries

```
npm install connect-timeout
npm install express@2.5.11
npm install mongoose@1.8.4
npm install jade
```

The output should be:

```
root@Config61288VM0:~/express-osc# npm install connect-timeout
npm WARN package.json application-name@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/connect-timeout/0.0.1
npm http 304 https://registry.npmjs.org/connect-timeout/0.0.1
connect-timeout@0.0.1 node_modules/connect-timeout
root@Config61288VM0:~/express-osc# npm install express@2.5.11
npm WARN package.json application-name@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/express/2.5.11
npm http 304 https://registry.npmjs.org/express/2.5.11
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/mime/1.2.4
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/mkdirp/0.3.0
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/qs
npm WARN package.json connect@1.9.2 No README.md file found!
npm http 304 https://registry.npmjs.org/mkdirp/0.3.0
npm http 304 https://registry.npmjs.org/mime/1.2.4
npm http GET https://registry.npmjs.org/formidable
npm http 304 https://registry.npmjs.org/formidable
express@2.5.11 node_modules/express
├── qs@0.4.2
├── mkdirp@0.3.0
├── mime@1.2.4
└── connect@1.9.2 (formidable@1.0.11)
root@Config61288VM0:~/express-osc# npm install mongoose@1.8.4
npm WARN package.json application-name@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/mongoose/1.8.4
npm http 304 https://registry.npmjs.org/mongoose/1.8.4
npm http GET https://registry.npmjs.org/hooks/0.1.9
npm http GET https://registry.npmjs.org/mongodb/0.9.6-7
npm http GET https://registry.npmjs.org/colors/0.5.0
npm http 304 https://registry.npmjs.org/hooks/0.1.9
npm http 304 https://registry.npmjs.org/mongodb/0.9.6-7
npm http 304 https://registry.npmjs.org/colors/0.5.0

> mongodb@0.9.6-7 install /root/express-osc/node_modules/mongoose/node_modules/mongodb
> bash ./install.sh

================================================================================
=                                                                              =
=  To install with C++ bson parser do <npm install mongodb --mongodb:native>   =
=  the parser only works for node 0.4.X or lower                               =
=                                                                              =
================================================================================
Not building native library for cygwin
mongoose@1.8.4 node_modules/mongoose
├── colors@0.5.0
├── hooks@0.1.9
└── mongodb@0.9.6-7
root@Config61288VM0:~/express-osc# npm install jade
npm WARN package.json application-name@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/jade
npm http 304 https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/commander/0.6.1
npm http 304 https://registry.npmjs.org/mkdirp
jade@0.27.4 node_modules/jade
├── commander@0.6.1
└── mkdirp@0.3.4
```

Then launch the app

```
node app.js
```

The effort to update those to the latest express and mongoose should be like half day as I need to learn the new way of doing things. Unfortunately I am in the middle of my office work.

**Comment by SakuraCart** [comment]
Thanks! I got up and running!
Now, I just have to try to use it.
